name = "verifai-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "verifai-db"
database_id = "f72f951d-2beb-4521-a1b1-b0aad1077ba3"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "verifai-uploads"

[triggers]
crons = ["0 * * * *"]

[vars]
REPORT_TTL_HOURS = "24"
